name: Backend Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x  # Specify the .NET version you are using

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.12.1  # Specify the Node.js version you are using (if needed)

      - name: Restore and Build Backend
        run: |
          dotnet restore
          dotnet build --no-restore

      # You can add additional steps here for running tests, code analysis, etc.

      - name: Publish Backend
        run: |
          dotnet publish backend-app.csproj --configuration Release --output ./publish

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.2
        with: 
          branch: gh-pages  # Specify the branch where you want to deploy
          folder: ./publish  # Set the folder containing the published files
          #token: ${{secrets.TOKEN}}
